name: Continuous Deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/README.md"

jobs:
  build_project:
    name: Build
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
      node-version: 16
    - run: npm ci
    - run: npm i -g firebase-tools
    - run: npm test
    - run: npm run build
    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  deploy_project:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
          with:
            name: build
            path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
